"""Typed artifact contracts exchanged between graph nodes."""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ArtifactModel(BaseModel):
    """Base model for all graph artifacts."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["v1"] = "v1"


class VideoSummary(ArtifactModel):
    """Compact per-video summary context from ingestion."""

    filename: str
    duration_s: float = Field(default=0.0, ge=0.0)
    summary: str = ""


class PlanningInput(ArtifactModel):
    """Typed input context for planning/research/clarification nodes."""

    summaries: list[VideoSummary] = Field(default_factory=list)
    request_id: str = ""


class AnswerSet(ArtifactModel):
    """Typed user answer payload for verification stage."""

    answers: dict[str, str] = Field(default_factory=dict)


class IntentBrief(ArtifactModel):
    """User intent and constraints extracted during planning."""

    summary: str
    goals: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)


class ResearchEvidence(ArtifactModel):
    """Evidence item backing a research finding."""

    source: str
    quote: str
    confidence: float = Field(ge=0.0, le=1.0)


class ResearchFinding(ArtifactModel):
    """Single finding tied to one or more evidence items."""

    claim: str
    evidence: list[ResearchEvidence] = Field(default_factory=list)


class ResearchPack(ArtifactModel):
    """Collected findings and unresolved ambiguities."""

    findings: list[ResearchFinding] = Field(default_factory=list)
    unresolved: list[str] = Field(default_factory=list)


class ClarifyingQuestion(ArtifactModel):
    """A single question to ask the user."""

    id: str
    text: str
    options: list[str] | None = None
    rationale: str = ""


class Storyline(ArtifactModel):
    """Candidate narrative direction produced by clarification."""

    title: str
    description: str


class QuestionSet(ArtifactModel):
    """Question bundle generated by clarification."""

    analysis: str = ""
    intro: str = ""
    suggested_storylines: list[Storyline] = Field(default_factory=list)
    questions: list[ClarifyingQuestion] = Field(default_factory=list)
    max_questions: int = Field(default=4, ge=1, le=12)


class UserApproval(ArtifactModel):
    """Captures user approval/revision state."""

    status: Literal["pending", "approved", "rejected", "revised"] = "pending"
    feedback: str = ""
    revision_notes: list[str] = Field(default_factory=list)


class EditClip(ArtifactModel):
    """Clip-level editing decision."""

    source_video: str
    start_s: float = Field(ge=0.0)
    end_s: float = Field(gt=0.0)
    reason: str = ""


class EditSpec(ArtifactModel):
    """Structured edit instructions before composition synthesis."""

    narrative: str = ""
    clips: list[EditClip] = Field(default_factory=list)
    subtitle_notes: list[str] = Field(default_factory=list)
    overlay_notes: list[str] = Field(default_factory=list)
    audio_notes: list[str] = Field(default_factory=list)


class CompositionDraft(ArtifactModel):
    """Intermediate composition payload before final rendering."""

    timeline: dict[str, Any] = Field(default_factory=dict)
    composition: dict[str, Any] = Field(default_factory=dict)
    warnings: list[str] = Field(default_factory=list)


class VerificationIssue(ArtifactModel):
    """Structured issue emitted by verification nodes."""

    severity: Literal["info", "warning", "error"]
    code: str
    message: str
    field: str | None = None


class VerificationReport(ArtifactModel):
    """Validation result for internal or final verification."""

    passed: bool = False
    issues: list[VerificationIssue] = Field(default_factory=list)


class RenderReadiness(ArtifactModel):
    """Final render readiness token."""

    ready: bool = False
    reasons: list[str] = Field(default_factory=list)


class StructuredPromptArtifact(ArtifactModel):
    """Structured prompt output for downstream editing."""

    status: Literal["ready", "pending"] = "pending"
    structured_prompt: str = ""


class ArtifactBundle(BaseModel):
    """Container for all cross-node artifacts."""

    model_config = ConfigDict(extra="forbid")

    planning_input: PlanningInput | None = None
    answer_set: AnswerSet | None = None
    intent_brief: IntentBrief | None = None
    research_pack: ResearchPack | None = None
    question_set: QuestionSet | None = None
    user_approval: UserApproval | None = None
    structured_prompt: StructuredPromptArtifact | None = None
    edit_spec: EditSpec | None = None
    composition_draft: CompositionDraft | None = None
    verification_report: VerificationReport | None = None
    render_readiness: RenderReadiness | None = None
